<?php
echo "dvcb 1 " . " = " . hash('ripemd160', 'dvcb 1');
echo '<br>';
echo "dvcb 2 " . " = " . hash('ripemd160', 'dvcb 2');
echo '<br>';
echo "dvcb 3 " . " = " . hash('ripemd160', 'dvcb 3');
echo '<br>';
echo "dvcb 4 " . " = " . hash('ripemd160', 'dvcb 4');
echo '<br>';
echo '<br>';
echo "dvcg 1 " . " = " . hash('ripemd160', 'dvcg 1');
echo '<br>';
echo "dvcg 2 " . " = " . hash('ripemd160', 'dvcg 2');
echo '<br>';
echo "dvcg 3 " . " = " . hash('ripemd160', 'dvcg 3');
echo '<br>';
echo "dvcg 4 " . " = " . hash('ripemd160', 'dvcg 4');
echo '<br>';
echo '<br>';
echo "vcb 1 " . " = " . hash('ripemd160', 'vcb 1');
echo '<br>';
echo "vcb 2 " . " = " . hash('ripemd160', 'vcb 2');
echo '<br>';
echo "vcb 3 " . " = " . hash('ripemd160', 'vcb 3');
echo '<br>';
echo "vcb 4 " . " = " . hash('ripemd160', 'vcb 4');
echo '<br>';
echo '<br>';
echo "vcg 1 " . " = " . hash('ripemd160', 'vcg 1');
echo '<br>';
echo "vcg 2 " . " = " . hash('ripemd160', 'vcg 2');
echo '<br>';
echo "vcg 3 " . " = " . hash('ripemd160', 'vcg 3');
echo '<br>';
echo "vcg 4 " . " = " . hash('ripemd160', 'vcg 4');
echo '<br>';
echo '<br>';
echo "dcb 1 " . " = " . hash('ripemd160', 'dcb 1');
echo '<br>';
echo "dcb 2 " . " = " . hash('ripemd160', 'dcb 2');
echo '<br>';
echo "dcb 3 " . " = " . hash('ripemd160', 'dcb 3');
echo '<br>';
echo "dcb 4 " . " = " . hash('ripemd160', 'dcb 4');
echo '<br>';
echo '<br>';
echo "dcg 1 " . " = " . hash('ripemd160', 'dcg 1');
echo '<br>';
echo "dcg 2 " . " = " . hash('ripemd160', 'dcg 2');
echo '<br>';
echo "dcg 3 " . " = " . hash('ripemd160', 'dcg 3');
echo '<br>';
echo "dcg 4 " . " = " . hash('ripemd160', 'dcg 4');
echo '<br>';
echo '<br>';
echo "cb 1 " . " = " . hash('ripemd160', 'cb 1');
echo '<br>';
echo "cb 2 " . " = " . hash('ripemd160', 'cb 2');
echo '<br>';
echo "cb 3 " . " = " . hash('ripemd160', 'cb 3');
echo '<br>';
echo "cb 4 " . " = " . hash('ripemd160', 'cb 4');
echo '<br>';
echo '<br>';
echo "cg 1 " . " = " . hash('ripemd160', 'cg 1');
echo '<br>';
echo "cg 2 " . " = " . hash('ripemd160', 'cg 2');
echo '<br>';
echo "cg 3 " . " = " . hash('ripemd160', 'cg 3');
echo '<br>';
echo "cg 4 " . " = " . hash('ripemd160', 'cg 4');
echo '<br>';
echo '<br>';
 